import React from "react";
import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft, Shield, Lock, HardDrive, Megaphone, Eye, Server } from "lucide-react";
import { publicEnv } from "@/lib/env";

export const metadata: Metadata = {
  title: "Privacy Policy | Vasuki Publication",
  description:
    "Privacy Policy for Vasuki Publication. Learn how we handle browser-local saved books, anonymous reading, native advertisements, and operational security.",
  alternates: {
    canonical: `${publicEnv.NEXT_PUBLIC_SITE_URL}/privacy`,
  },
  openGraph: {
    title: "Privacy Policy | Vasuki Publication",
    description: "Privacy practices and local storage policies for Vasuki Publication.",
    url: `${publicEnv.NEXT_PUBLIC_SITE_URL}/privacy`,
  },
};

export default function PrivacyPage() {
  const lastUpdated = "September 15, 2026";

  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-10 sm:py-16">
      {/* Breadcrumb & Navigation */}
      <nav className="flex items-center gap-2 text-xs font-mono text-mute mb-8" aria-label="Breadcrumb">
        <Link
          href="/"
          className="inline-flex items-center gap-1.5 hover:text-ink transition-colors focus-visible:outline-hidden focus-visible:ring-2 focus-visible:ring-brand rounded-xs"
        >
          <ArrowLeft className="w-3.5 h-3.5" />
          <span>Home</span>
        </Link>
        <span>/</span>
        <span className="text-ink font-medium">Privacy Policy</span>
      </nav>

      {/* Header */}
      <header className="pb-8 border-b border-border/60 mb-10">
        <div className="inline-flex items-center gap-2 px-2.5 py-1 rounded-full bg-emerald-500/10 text-emerald-700 text-xs font-mono font-medium mb-3">
          <Shield className="w-3.5 h-3.5" />
          <span>Privacy & Transparency</span>
        </div>
        <h1 className="text-3xl sm:text-4xl font-black tracking-tight text-ink font-sans">
          Privacy Policy
        </h1>
        <p className="text-xs font-mono text-mute mt-2">
          Last Updated: {lastUpdated}
        </p>
      </header>

      {/* Content Body */}
      <div className="space-y-10 text-sm leading-relaxed text-ink/90 font-sans">
        {/* Section 1: Core Philosophy */}
        <section className="space-y-3">
          <h2 className="text-lg font-bold text-ink tracking-tight flex items-center gap-2">
            <Lock className="w-4 h-4 text-brand" />
            1. Reader Privacy Philosophy
          </h2>
          <p>
            Vasuki Publication is designed as a public, open-access reading platform for technical books and architectural handbooks generated by VasukiSquare. We believe reading should be private, anonymous, and frictionless.
          </p>
          <div className="p-4 rounded-xl bg-[#f6f8fa] border border-border/60 text-xs space-y-1.5">
            <p className="font-semibold text-ink">Zero Reader Accounts:</p>
            <p className="text-mute">
              We do not require or offer user registration, reader accounts, or profile creation for reading public publications. You can browse, search, and read every published book without providing an email address, name, or password.
            </p>
          </div>
        </section>

        {/* Section 2: Browser-Local Storage */}
        <section className="space-y-3">
          <h2 className="text-lg font-bold text-ink tracking-tight flex items-center gap-2">
            <HardDrive className="w-4 h-4 text-brand" />
            2. Browser-Local Saved Books (localStorage)
          </h2>
          <p>
            When you save a publication for quick reference or offline reading via the bookmark button, that state is stored strictly on your local device using standard HTML5 <code className="px-1.5 py-0.5 rounded bg-slate-100 text-xs font-mono text-ink">localStorage</code> under the key <code className="px-1.5 py-0.5 rounded bg-slate-100 text-xs font-mono text-ink">vasuki.savedBooks.v1</code>.
          </p>
          <ul className="list-disc list-inside space-y-1.5 text-xs text-ink/80 pl-2">
            <li>Your saved books list is never transmitted, synchronized, or stored on our servers.</li>
            <li>No database profile or identity identifier links your browser to the books you save.</li>
            <li>You can clear your saved reading list at any time directly through the Saved Books page or your browser&apos;s site data settings.</li>
          </ul>
        </section>

        {/* Section 3: Native Advertisements */}
        <section className="space-y-3">
          <h2 className="text-lg font-bold text-ink tracking-tight flex items-center gap-2">
            <Megaphone className="w-4 h-4 text-brand" />
            3. Native Advertisements & External Links
          </h2>
          <p>
            To support ongoing hosting and operational costs, Vasuki Publication displays restrained, native sponsor cards in website discovery spaces (homepage banner/sidebar and saved page banner/sidebar).
          </p>
          <div className="space-y-2 text-xs text-ink/80">
            <p>
              <strong className="text-ink">Zero Reader Tracking:</strong> We do not use third-party ad networks, tracking pixels, behavioral retargeting scripts, or cross-site tracking cookies.
            </p>
            <p>
              <strong className="text-ink">Aggregate Metrics:</strong> When an advertisement is viewed or clicked, we increment an anonymous aggregate counter (<code className="font-mono">impressions</code> and <code className="font-mono">clicks</code>) on the advertisement document in MongoDB. No IP addresses, user agents, or personal identities are attached to these counters.
            </p>
            <p>
              <strong className="text-ink">Outbound Confirmation Modal:</strong> All external sponsor links open via an explicit security confirmation dialog requiring confirmation before navigating off-site, opening with <code className="font-mono">rel=&quot;noopener noreferrer nofollow&quot;</code>.
            </p>
            <p>
              <strong className="text-ink">No Reader Ads Invariant:</strong> Advertisements are strictly prohibited inside the interactive book reader (<code className="font-mono">/book/[slug]/read</code>).
            </p>
          </div>
        </section>

        {/* Section 4: Operational Security & Admin Access */}
        <section className="space-y-3">
          <h2 className="text-lg font-bold text-ink tracking-tight flex items-center gap-2">
            <Server className="w-4 h-4 text-brand" />
            4. Operational Security & Server Logs
          </h2>
          <p>
            Standard technical server logs (such as HTTP request path, response status, and approximate timestamp) are maintained by hosting providers (such as Vercel) for server health diagnostics, error monitoring, and DDoS/abuse mitigation.
          </p>
          <p className="text-xs text-mute">
            Administrative access beneath <code className="font-mono">/admin</code> is protected by secret token authentication and signed <code className="font-mono">HttpOnly</code> session cookies. Brute-force rate limiting is applied to administrative login attempts to protect backend integrity.
          </p>
        </section>

        {/* Section 5: Third-Party Infrastructure */}
        <section className="space-y-3">
          <h2 className="text-lg font-bold text-ink tracking-tight flex items-center gap-2">
            <Eye className="w-4 h-4 text-brand" />
            5. Hosting & Data Processors
          </h2>
          <p>
            The application is hosted on cloud infrastructure providers (Vercel and MongoDB Atlas). Data transmitted during your browsing sessions is encrypted in transit using industry-standard TLS/HTTPS protocols.
          </p>
        </section>

        {/* Section 6: Policy Changes */}
        <section className="space-y-3">
          <h2 className="text-lg font-bold text-ink tracking-tight">
            6. Changes to this Policy
          </h2>
          <p>
            We may update this Privacy Policy from time to time to reflect modifications in platform functionality or hosting configurations. The revised date at the top of this document will always indicate the effective date of changes.
          </p>
        </section>
      </div>

      {/* Footer link back */}
      <div className="mt-12 pt-6 border-t border-border/60 flex items-center justify-between text-xs text-mute font-mono">
        <Link href="/" className="hover:text-ink transition-colors">
          ← Return to Discovery
        </Link>
        <Link href="/terms" className="hover:text-ink transition-colors">
          Terms of Service →
        </Link>
      </div>
    </div>
  );
}

