import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SiteHeader } from "@/components/layout/SiteHeader";
import { SiteFooter } from "@/components/layout/SiteFooter";
import { publicEnv } from "@/lib/env";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  metadataBase: new URL(publicEnv.NEXT_PUBLIC_SITE_URL),
  title: {
    default: "Vasuki Publication — Web Platform for VasukiSquare Books",
    template: "%s | Vasuki Publication",
  },
  description:
    "Official public reading and publishing platform for books generated by VasukiSquare. Zero-PDF native web streaming, rich typography, and instant topic discovery.",
  keywords: [
    "VasukiSquare",
    "Vasuki Publication",
    "Technical Books",
    "Architecture Guides",
    "Programming Books",
    "Developer Handbooks",
  ],
  authors: [{ name: "Swaraj Puppalwar" }],
  creator: "Swaraj Puppalwar",
  publisher: "Vasuki Publication",
  openGraph: {
    type: "website",
    locale: "en_US",
    url: publicEnv.NEXT_PUBLIC_SITE_URL,
    siteName: "Vasuki Publication",
    title: "Vasuki Publication — Web Platform for VasukiSquare Books",
    description:
      "Official public reading platform for books generated by VasukiSquare. Zero-PDF native web streaming and instant topic discovery.",
  },
  twitter: {
    card: "summary_large_image",
    title: "Vasuki Publication — Web Platform for VasukiSquare Books",
    description:
      "Official public reading platform for books generated by VasukiSquare.",
  },
  robots: {
    index: true,
    follow: true,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-white text-ink font-sans selection:bg-ink selection:text-white">
        <SiteHeader />
        <main className="flex-1 w-full">{children}</main>
        <SiteFooter />
      </body>
    </html>
  );
}
