import React from "react";
import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft, FileText, Globe, BookOpen, ExternalLink, AlertCircle, ShieldAlert } from "lucide-react";
import { publicEnv } from "@/lib/env";

export const metadata: Metadata = {
  title: "Terms of Service | Vasuki Publication",
  description:
    "Terms of Service governing the use of the Vasuki Publication public web platform, published content, and reading experience.",
  alternates: {
    canonical: `${publicEnv.NEXT_PUBLIC_SITE_URL}/terms`,
  },
  openGraph: {
    title: "Terms of Service | Vasuki Publication",
    description: "Terms of service and acceptable usage policies for Vasuki Publication.",
    url: `${publicEnv.NEXT_PUBLIC_SITE_URL}/terms`,
  },
};

export default function TermsPage() {
  const lastUpdated = "September 15, 2026";

  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-10 sm:py-16">
      {/* Breadcrumb & Navigation */}
      <nav className="flex items-center gap-2 text-xs font-mono text-mute mb-8" aria-label="Breadcrumb">
        <Link
          href="/"
          className="inline-flex items-center gap-1.5 hover:text-ink transition-colors focus-visible:outline-hidden focus-visible:ring-2 focus-visible:ring-brand rounded-xs"
        >
          <ArrowLeft className="w-3.5 h-3.5" />
          <span>Home</span>
        </Link>
        <span>/</span>
        <span className="text-ink font-medium">Terms of Service</span>
      </nav>

      {/* Header */}
      <header className="pb-8 border-b border-border/60 mb-10">
        <div className="inline-flex items-center gap-2 px-2.5 py-1 rounded-full bg-emerald-500/10 text-emerald-700 text-xs font-mono font-medium mb-3">
          <FileText className="w-3.5 h-3.5" />
          <span>Platform Agreement</span>
        </div>
        <h1 className="text-3xl sm:text-4xl font-black tracking-tight text-ink font-sans">
          Terms of Service
        </h1>
        <p className="text-xs font-mono text-mute mt-2">
          Last Updated: {lastUpdated}
        </p>
      </header>

      {/* Content Body */}
      <div className="space-y-10 text-sm leading-relaxed text-ink/90 font-sans">
        {/* Section 1: Overview & Scope */}
        <section className="space-y-3">
          <h2 className="text-lg font-bold text-ink tracking-tight flex items-center gap-2">
            <Globe className="w-4 h-4 text-brand" />
            1. Agreement to Terms & Scope
          </h2>
          <p>
            These Terms of Service (&quot;Terms&quot;) govern your access to and use of the <strong>Vasuki Publication</strong> website and online reader platform (<code className="font-mono text-xs">{publicEnv.NEXT_PUBLIC_SITE_URL}</code>). By browsing, searching, or reading publications on this site, you agree to be bound by these Terms.
          </p>
          <div className="p-4 rounded-xl bg-amber-500/10 border border-amber-500/20 text-xs space-y-1.5 text-amber-900">
            <p className="font-semibold flex items-center gap-1.5">
              <AlertCircle className="w-4 h-4 text-amber-600 shrink-0" />
              Source Code vs. Website Terms Distinction:
            </p>
            <p>
              These website terms govern the public presentation website and reader experience. The underlying software source code of VasukiSquare and VasukiPublication is governed separately by the <strong>VASUKISQUARE COMMERCIAL SOURCE LICENSE Version 1.0</strong> as set forth in the repository LICENSE file.
            </p>
          </div>
        </section>

        {/* Section 2: Public Website Access */}
        <section className="space-y-3">
          <h2 className="text-lg font-bold text-ink tracking-tight flex items-center gap-2">
            <BookOpen className="w-4 h-4 text-brand" />
            2. Public Reading Platform & Published Content
          </h2>
          <p>
            Vasuki Publication is an open reading platform for technical books, architectural handbooks, and reference literature generated by the VasukiSquare authoring engine.
          </p>
          <ul className="list-disc list-inside space-y-1.5 text-xs text-ink/80 pl-2">
            <li><strong>Informational Purpose:</strong> Publications are provided for educational and reference purposes. While books are authored and structured to high technical standards, authors and publishers do not guarantee error-free code or absolute fitness for specific production deployments.</li>
            <li><strong>Browser-Based Reading:</strong> The website reconstructs books directly from structured database documents without PDF dependencies. Readers are granted permission to view and bookmark content for personal and professional study.</li>
            <li><strong>Intellectual Property:</strong> Book titles, cover designs, structured editorial layouts, and accompanying media remain the property of their respective copyright holders and authors.</li>
          </ul>
        </section>

        {/* Section 3: Acceptable Use & Prohibited Conduct */}
        <section className="space-y-3">
          <h2 className="text-lg font-bold text-ink tracking-tight flex items-center gap-2">
            <ShieldAlert className="w-4 h-4 text-brand" />
            3. Acceptable Use & Prohibited Actions
          </h2>
          <p>
            When utilizing Vasuki Publication, you agree not to engage in any of the following prohibited behaviors:
          </p>
          <ul className="list-disc list-inside space-y-1.5 text-xs text-ink/80 pl-2">
            <li>Interfering with, disrupting, or imposing an unreasonable or disproportionately large load on platform infrastructure or database connections.</li>
            <li>Attempting to bypass authentication mechanisms, probe administrative endpoints beneath <code className="font-mono">/admin</code>, or forge session signatures.</li>
            <li>Using automated scrapers or bots in a manner that degrades service availability for other users.</li>
            <li>Framing or mirroring website chrome in a manner that misrepresents platform provenance or authorship.</li>
          </ul>
        </section>

        {/* Section 4: External Links & Sponsored Content */}
        <section className="space-y-3">
          <h2 className="text-lg font-bold text-ink tracking-tight flex items-center gap-2">
            <ExternalLink className="w-4 h-4 text-brand" />
            4. External Links & Sponsored Content
          </h2>
          <p>
            The website may contain native promotional cards or references to third-party tools, services, and websites. Vasuki Publication does not endorse or assume liability for third-party products, external terms, or privacy practices. Outbound sponsor links require explicit user confirmation before redirecting.
          </p>
        </section>

        {/* Section 5: Disclaimers & Limitation of Liability */}
        <section className="space-y-3">
          <h2 className="text-lg font-bold text-ink tracking-tight">
            5. Disclaimers & Limitation of Liability
          </h2>
          <p className="text-xs text-mute uppercase font-mono tracking-wider font-semibold">
            Provided &quot;As Is&quot; Without Warranty
          </p>
          <p className="text-xs text-ink/80">
            THE PLATFORM, ALL PUBLICATIONS, COVERS, CODE SAMPLES, AND RELATED CONTENT ARE PROVIDED ON AN &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; BASIS WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED. TO THE MAXIMUM EXTENT PERMITTED UNDER APPLICABLE LAW, VASUKI PUBLICATION AND ITS CONTRIBUTORS DISCLAIM ALL WARRANTIES INCLUDING MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
          </p>
        </section>

        {/* Section 6: Modifications */}
        <section className="space-y-3">
          <h2 className="text-lg font-bold text-ink tracking-tight">
            6. Modifications to Service & Terms
          </h2>
          <p>
            We reserve the right to modify or discontinue features, publications, or these Terms at any time. Continued use of the platform following updates constitutes acceptance of the modified Terms.
          </p>
        </section>
      </div>

      {/* Footer link back */}
      <div className="mt-12 pt-6 border-t border-border/60 flex items-center justify-between text-xs text-mute font-mono">
        <Link href="/" className="hover:text-ink transition-colors">
          ← Return to Discovery
        </Link>
        <Link href="/privacy" className="hover:text-ink transition-colors">
          Privacy Policy →
        </Link>
      </div>
    </div>
  );
}

