import React from "react";
import Link from "next/link";
import type { Book, Cover } from "@/lib/types/publication";
import { CoverPreview } from "@/components/cover/CoverPreview";
import { SaveBookButton } from "./SaveBookButton";
import { BookOpen, Layers, ArrowUpRight } from "lucide-react";

interface BookCardProps {
  book: Book;
  cover?: Cover | null;
  className?: string;
}

export function BookCard({ book, cover, className = "" }: BookCardProps) {
  const category = book.category || book.discovery?.category || "Technical";
  const pageCount = book.page_count || 0;
  const chapterCount = book.chapter_count || (book.chapters?.length ?? 0);
  const description = book.description || book.subtitle || "Comprehensive guide generated by VasukiSquare.";

  return (
    <div
      className={`group relative bg-white border border-hairline hover:border-hairline-strong rounded-xl p-4 transition-all duration-200 hover:shadow-md flex flex-col justify-between ${className}`}
    >
      <div>
        {/* Top: Cover Preview Link */}
        <Link
          href={`/book/${book.slug}`}
          className="block w-full flex justify-center py-2 bg-canvas-soft rounded-lg border border-hairline group-hover:border-hairline-strong transition-colors overflow-hidden relative"
        >
          <div className="group-hover:scale-103 transition-transform duration-200">
            <CoverPreview book={book} cover={cover} size="md" />
          </div>
        </Link>

        {/* Category & Save Button */}
        <div className="flex items-center justify-between mt-3.5 mb-2">
          <span className="text-[10px] font-mono uppercase tracking-wider text-mute bg-canvas-soft px-2 py-0.5 rounded border border-hairline font-semibold">
            {category}
          </span>
          <SaveBookButton book={book} variant="icon" />
        </div>

        {/* Title */}
        <h3 className="text-sm font-semibold text-ink line-clamp-2 leading-snug group-hover:text-link transition-colors">
          <Link href={`/book/${book.slug}`} className="hover:underline">
            {book.title}
          </Link>
        </h3>

        {/* Subtitle / Excerpt */}
        <p className="mt-1.5 text-xs text-body line-clamp-2 leading-relaxed">
          {description}
        </p>
      </div>

      {/* Footer Metrics & Actions */}
      <div className="mt-4 pt-3 border-t border-hairline flex items-center justify-between text-xs text-mute font-mono">
        <div className="flex items-center gap-3">
          {pageCount > 0 && (
            <span className="flex items-center gap-1" title={`${pageCount} pages`}>
              <BookOpen className="w-3 h-3 text-mute" />
              <span>{pageCount}p</span>
            </span>
          )}
          {chapterCount > 0 && (
            <span className="flex items-center gap-1" title={`${chapterCount} chapters`}>
              <Layers className="w-3 h-3 text-mute" />
              <span>{chapterCount}ch</span>
            </span>
          )}
        </div>

        <Link
          href={`/book/${book.slug}`}
          className="inline-flex items-center gap-0.5 text-ink font-semibold group-hover:translate-x-0.5 transition-transform"
        >
          <span>Read</span>
          <ArrowUpRight className="w-3.5 h-3.5" />
        </Link>
      </div>
    </div>
  );
}
