"use client";

import React from "react";
import { VasukiBlockRenderer } from "@/components/reader/VasukiBlockRenderer";
import { VasukiHtmlRenderer } from "@/components/reader/VasukiHtmlRenderer";
import { VasukiIcon } from "@/components/vasuki/VasukiIcon";
import type { Page, Book } from "@/lib/types/publication";

interface VasukiBookPageProps {
  page: Page;
  book: Pick<Book, "title" | "subtitle" | "author" | "running_title" | "page_count">;
  themeOverride?: "light" | "dark" | "sepia" | null;
  className?: string;
}

/**
 * High-fidelity VasukiBookPage renderer reproducing exact VasukiSquare layout,
 * typography, dual-mode themes, and component styling ("ditto copy").
 */
export function VasukiBookPage({
  page,
  book,
  themeOverride,
  className = "",
}: VasukiBookPageProps) {
  // Determine effective theme
  const effectiveTheme =
    themeOverride === "dark" || themeOverride === "light"
      ? themeOverride
      : (page.style?.theme as "light" | "dark") ||
        (page.theme as "light" | "dark") ||
        "light";

  const isCover =
    page.page_type === "cover" ||
    page.layout === "cover" ||
    page.page_number === 1;

  const isChapterOpener =
    page.page_type === "chapter_opener" ||
    page.layout === "chapter_opener" ||
    (!isCover && Boolean(page.chapter_number && page.content?.headline && !page.content?.body && (page.content?.blocks?.length ?? 0) <= 2));

  const isTitlePage =
    !isCover &&
    (page.page_type === "title" ||
      page.page_type === "imprint" ||
      page.layout === "title" ||
      page.layout === "imprint" ||
      page.page_number === 2);

  const isThankYou =
    !isCover &&
    (page.page_type === "thank_you" ||
      page.layout === "thank_you" ||
      (Boolean(book.page_count) && page.page_number === book.page_count && !isChapterOpener));

  const layoutType =
    page.layout ||
    (isCover
      ? "cover"
      : isChapterOpener
      ? "chapter_opener"
      : isTitlePage
      ? "title"
      : isThankYou
      ? "thank_you"
      : "editorial_standard");

  const hasStructuredBlocks = Boolean(page.content?.blocks && page.content.blocks.length > 0);
  const hasPreRenderedHtml = Boolean(page.html && page.html.trim().length > 0);

  // If page.html contains a full outer .page container generated by VasukiSquare
  if (hasPreRenderedHtml && page.html!.includes('class="page')) {
    return (
      <div className={`vasuki-book-root w-full h-full flex items-center justify-center select-text ${className}`}>
        <VasukiHtmlRenderer html={page.html!} />
      </div>
    );
  }

  const hideHeaderFooter = isCover || isChapterOpener || isThankYou;

  return (
    <div className={`vasuki-book-root w-full h-full flex items-center justify-center select-text ${className}`}>
      <div
        className={`page theme-${effectiveTheme} layout-${layoutType}`}
        data-page-number={page.page_number}
        style={page.style ? ({ ...page.style } as React.CSSProperties) : undefined}
      >
        <div className="page-safe-content">
          {/* =========================================================================
              1. PAGE HEADER (Hidden on Cover, Chapter Opener, Thank You)
             ========================================================================= */}
          {!hideHeaderFooter && (
            <header className="page-header">
              <span className="header-chapter">
                {page.chapter_number
                  ? `Chapter ${page.chapter_number}: ${page.chapter_title || ""}`
                  : page.chapter_title || ""}
              </span>
              <span className="header-topic">
                {book.running_title || book.title}
              </span>
            </header>
          )}

          {/* =========================================================================
              2. PAGE MAIN CONTENT
             ========================================================================= */}
          <main className="page-content custom-scrollbar">
            {/* A. Full-Bleed Cover Layout */}
            {isCover && (
              <>
                {hasPreRenderedHtml ? (
                  <VasukiHtmlRenderer html={page.html!} />
                ) : (
                  <div
                    className="cover-hero cover-hero-solid"
                    style={{
                      backgroundColor: "#f9fbfa",
                      padding: "40px 36px 80px 36px",
                      display: "flex",
                      flexDirection: "column",
                      justifyContent: "space-between",
                      height: "100%",
                      width: "100%",
                      boxSizing: "border-box",
                      position: "relative",
                      overflow: "hidden",
                    }}
                  >
                    {/* Background geometric svg layer */}
                    <div
                      className="vector-scenery-layer"
                      style={{
                        position: "absolute",
                        inset: 0,
                        width: "100%",
                        height: "100%",
                        pointerEvents: "none",
                        zIndex: 1,
                        opacity: 0.18,
                      }}
                    >
                      <svg
                        viewBox="0 0 794 1123"
                        width="100%"
                        height="100%"
                        xmlns="http://www.w3.org/2000/svg"
                        preserveAspectRatio="none"
                      >
                        <circle
                          cx="397"
                          cy="591"
                          r="120"
                          fill="none"
                          stroke="#001e2b"
                          strokeWidth="2"
                          strokeDasharray="4 4"
                        />
                        <circle
                          cx="397"
                          cy="591"
                          r="70"
                          fill="#00ed64"
                          fillOpacity="0.12"
                          stroke="#00ed64"
                          strokeWidth="2"
                        />
                        <path
                          d="M 0 1123 L 0 750 Q 397 680 794 750 L 794 1123 Z"
                          fill="#001e2b"
                          opacity="0.08"
                        />
                      </svg>
                    </div>

                    {/* Top brand header */}
                    <div
                      style={{
                        position: "relative",
                        zIndex: 2,
                        display: "flex",
                        justifyContent: "space-between",
                        alignItems: "center",
                      }}
                    >
                      <div
                        className="cover-category-badge"
                        style={{
                          fontSize: "10px",
                          fontWeight: 700,
                          letterSpacing: "1.5px",
                          textTransform: "uppercase",
                          color: "#ffffff",
                          backgroundColor: "#001e2b",
                          padding: "4px 10px",
                          borderRadius: "3px",
                          border: "1px solid rgba(255, 255, 255, 0.12)",
                          boxShadow: "0 2px 6px rgba(0, 0, 0, 0.25)",
                          display: "inline-block",
                        }}
                      >
                        VASUKISQUARE EDITION
                      </div>
                      <div className="w-8 h-8 rounded-full bg-emerald-500/10 text-emerald-600 flex items-center justify-center">
                        <VasukiIcon name={page.icon || "BookOpen"} size={18} />
                      </div>
                    </div>

                    {/* Title Box */}
                    <div
                      style={{
                        position: "relative",
                        zIndex: 2,
                        margin: "auto 0",
                        display: "flex",
                        flexDirection: "column",
                        alignItems: "flex-start",
                      }}
                    >
                      <div
                        className="cover-title-container"
                        style={{
                          backgroundColor: "#001e2b",
                          padding: "24px 28px",
                          borderRadius: "4px",
                          border: "1px solid rgba(255, 255, 255, 0.12)",
                          boxShadow: "0 10px 20px -8px rgba(0, 0, 0, 0.4)",
                          display: "flex",
                          flexDirection: "column",
                          alignItems: "flex-start",
                          textAlign: "left",
                          gap: "12px",
                          width: "fit-content",
                          maxWidth: "100%",
                          boxSizing: "border-box",
                        }}
                      >
                        <h1
                          className="cover-title"
                          style={{
                            fontFamily: "var(--font-serif), Georgia, serif",
                            fontSize: "32px",
                            fontWeight: 700,
                            lineHeight: 1.15,
                            color: "#ffffff",
                            letterSpacing: "-0.5px",
                            maxWidth: "480px",
                            wordBreak: "break-word",
                            margin: 0,
                          }}
                        >
                          {book.title}
                        </h1>
                        <div
                          className="cover-divider"
                          style={{
                            width: "36px",
                            height: "2.5px",
                            backgroundColor: "#00ed64",
                            borderRadius: "1px",
                            opacity: 0.95,
                          }}
                        />
                        {book.subtitle && (
                          <p
                            className="cover-subtitle"
                            style={{
                              fontFamily: "var(--font-display), sans-serif",
                              fontSize: "13px",
                              fontWeight: 400,
                              lineHeight: 1.45,
                              color: "#cbd5e1",
                              maxWidth: "460px",
                              margin: 0,
                              wordBreak: "break-word",
                            }}
                          >
                            {book.subtitle}
                          </p>
                        )}
                      </div>
                    </div>

                    {/* Footer strip */}
                    <footer
                      className="cover-footer-strip"
                      style={{
                        position: "absolute",
                        bottom: 0,
                        left: 0,
                        right: 0,
                        width: "100%",
                        backgroundColor: "#001e2b",
                        zIndex: 10,
                        display: "flex",
                        justifyContent: "space-between",
                        alignItems: "center",
                        padding: "16px 36px",
                        boxSizing: "border-box",
                        borderTop: "1px solid rgba(255, 255, 255, 0.12)",
                      }}
                    >
                      <span
                        style={{
                          fontSize: "12px",
                          fontWeight: 700,
                          color: "#ffffff",
                          letterSpacing: "0.5px",
                        }}
                      >
                        {book.author || "Vasuki"}
                      </span>
                      <span
                        style={{
                          fontSize: "10px",
                          fontWeight: 500,
                          color: "#cbd5e1",
                          letterSpacing: "1.5px",
                          textTransform: "uppercase",
                        }}
                      >
                        DIGITAL WEB EDITION
                      </span>
                    </footer>
                  </div>
                )}
              </>
            )}

            {/* B. Chapter Opener Layout */}
            {!isCover && isChapterOpener && (
              <div className="chapter-opener-block">
                <div className="chapter-icon">
                  <VasukiIcon name={page.icon || "Sparkles"} size={56} />
                </div>
                <div className="chapter-num">
                  {page.chapter_number ? `Chapter ${page.chapter_number}` : "Chapter"}
                </div>
                <h1 className="chapter-title">
                  {page.chapter_title || page.content?.headline || "Chapter Introduction"}
                </h1>
                {page.content?.body && (
                  <p className="typo-lead" style={{ marginTop: "16px", maxWidth: "520px" }}>
                    {page.content.body}
                  </p>
                )}
                {hasStructuredBlocks && (
                  <div className="w-full text-left" style={{ marginTop: "24px" }}>
                    {page.content!.blocks!.map((block, idx) => (
                      <VasukiBlockRenderer key={idx} block={block} theme={effectiveTheme} />
                    ))}
                  </div>
                )}
                {!hasStructuredBlocks && hasPreRenderedHtml && (
                  <div className="w-full text-left" style={{ marginTop: "20px" }}>
                    <VasukiHtmlRenderer html={page.html!} />
                  </div>
                )}
              </div>
            )}

            {/* C. Title / Imprint Layout */}
            {!isCover && !isChapterOpener && isTitlePage && (
              <div className="title-page-container">
                <div className="title-page-header">
                  <span className="typo-eyebrow">VasukiSquare Architectural Series</span>
                </div>
                <div className="title-page-body">
                  <h1 className="title-page-title">{book.title}</h1>
                  <div className="title-page-divider" />
                  <p className="title-page-subtitle">
                    {book.subtitle || (page.content && page.content.body) || "A Definitive Architecture & Implementation Guide"}
                  </p>
                </div>
                <div className="title-page-imprint">
                  <p><strong>VasukiSquare Technical Publishing Engine</strong></p>
                  <p>Researched from primary authoritative sources and verified for production architectures.</p>
                  <p style={{ marginTop: "6px", fontSize: "11px", color: "var(--theme-text-subtle)" }}>
                    First Edition (2026) • All Rights Reserved
                  </p>
                </div>
              </div>
            )}

            {/* D. Thank You Page Layout */}
            {!isCover && !isChapterOpener && !isTitlePage && isThankYou && (
              <div className="thank-you-container">
                <div className="thank-you-brand">
                  <span>VASUKISQUARE TECHNICAL PUBLISHING</span>
                  <span>END OF VOLUME</span>
                </div>
                <div className="thank-you-body">
                  <div className="thank-you-icon">
                    <VasukiIcon name={page.icon || "CheckCircle2"} size={48} />
                  </div>
                  <div className="thank-you-divider" />
                  <h1 className="thank-you-title">
                    {page.content?.headline || "THANK YOU"}
                  </h1>
                  <p className="thank-you-statement">
                    {page.content?.body ||
                      "Thank you for reading. Researched from primary authoritative sources and rendered deterministically to physical A4 print specifications by VasukiSquare."}
                  </p>
                </div>
                <div className="thank-you-footer">
                  <span>{book.running_title || book.title}</span>
                  <span>FIRST EDITION</span>
                </div>
              </div>
            )}

            {/* E. Standard Editorial Page Layout */}
            {!isCover && !isChapterOpener && !isTitlePage && !isThankYou && (
              <>
                {page.content?.headline && (
                  <h2 className="content-headline">
                    {page.content.headline}
                  </h2>
                )}

                {hasStructuredBlocks && (
                  <div className="space-y-4">
                    {page.content!.blocks!.map((block, idx) => (
                      <VasukiBlockRenderer key={idx} block={block} theme={effectiveTheme} />
                    ))}
                  </div>
                )}

                {!hasStructuredBlocks && hasPreRenderedHtml && (
                  <VasukiHtmlRenderer html={page.html!} />
                )}

                {!hasStructuredBlocks && !hasPreRenderedHtml && page.content?.body && (
                  <div className="content-body">
                    {page.content.body.split("\n\n").map((para, i) => (
                      <p key={i}>{para}</p>
                    ))}
                  </div>
                )}
              </>
            )}
          </main>

          {/* =========================================================================
              3. PAGE FOOTER (Hidden on Cover, Chapter Opener, Thank You)
             ========================================================================= */}
          {!hideHeaderFooter && (
            <footer className="page-footer">
              <span className="footer-title">
                {book.running_title || book.title}
              </span>
              <span className="footer-page-num">{page.page_number}</span>
            </footer>
          )}
        </div>
      </div>
    </div>
  );
}
